version: '3.8'
services:

  postgres:
    image: postgres:latest
    container_name: jpapractice
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=market
      - POSTGRES_HOST=postgres
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadminpractice
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - "5050:80"
